/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 17pro.glb -T --types 
Files: 17pro.glb [9.59MB] > C:\programing Beginner tutorial\apple design\iphone2\public\model\17pro-transformed.glb [334.12KB] (97%)
*/

import * as THREE from "three";
import { JSX, useEffect, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import useIphoneAria from "@/threeField/zutandMan/Zutand";
import { noFlash } from "@/utils";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh;
    defaultMaterial001: THREE.Mesh;
    defaultMaterial002: THREE.Mesh;
    defaultMaterial003: THREE.Mesh;
    defaultMaterial004: THREE.Mesh;
    defaultMaterial005: THREE.Mesh;
    defaultMaterial006: THREE.Mesh;
    defaultMaterial007: THREE.Mesh;
    defaultMaterial009: THREE.Mesh;
    defaultMaterial010: THREE.Mesh;
    defaultMaterial011: THREE.Mesh;
    defaultMaterial012: THREE.Mesh;
    defaultMaterial013: THREE.Mesh;
    defaultMaterial014: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
  };
  materials: {
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    Glass_Camera_Logo: THREE.MeshStandardMaterial;
    Plastic: THREE.MeshStandardMaterial;
    Screen_Rim: THREE.MeshStandardMaterial;
    Grill_USB: THREE.MeshStandardMaterial;
    Camera_Pixel_Glass_002: THREE.MeshStandardMaterial;
    Camera_Pixel__002: THREE.MeshStandardMaterial;
    Rim_Buttons: THREE.MeshStandardMaterial;
    Flash_Glass_002: THREE.MeshStandardMaterial;
    Flash_002: THREE.MeshStandardMaterial;
    Screen_BG: THREE.MeshStandardMaterial;
    Screw: THREE.MeshStandardMaterial;
    Screen_Glass: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function Iphone17Pro(props: JSX.IntrinsicElements["group"]) {
  const texture = useTexture("/blackmode.jpg");
  const { color } = useIphoneAria();
  const { nodes, materials, scene } = useGLTF(
    "/model/17pro-transformed.glb"
  ) as unknown as GLTFResult;

  useEffect(() => {
    scene.traverse((child: THREE.Object3D) => {
      if ((child as THREE.Mesh).isMesh) {
        const mesh = child as THREE.Mesh;
        if (!noFlash.includes(mesh.name)) {
          if (Array.isArray(mesh.material)) {
            mesh.material.forEach((mat) => {
              if ("color" in mat)
                (mat as THREE.MeshStandardMaterial).color.set(color);
            });
          } else if (mesh.material) {
            (mesh.material as THREE.MeshStandardMaterial).color.set(color);
          }
        }
      }
    });
  }, [color, scene]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.004"]}
        position={[0.609, 1.661, -0.12]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.882}
      />
      <mesh
        geometry={nodes.defaultMaterial001.geometry}
        material={materials["Material.002"]}
        position={[0, 0, 0.043]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes.defaultMaterial002.geometry}
        material={materials.Glass_Camera_Logo}
        position={[-0.004, -0.012, -0.055]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes.defaultMaterial003.geometry}
        material={materials.Plastic}
        position={[0.609, 1.661, -0.108]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.027}
      />
      <mesh
        geometry={nodes.defaultMaterial004.geometry}
        material={materials.Screen_Rim}
        position={[0, 0, 0.043]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes.defaultMaterial005.geometry}
        material={materials.Grill_USB}
        position={[0, 0, 0.043]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes.defaultMaterial006.geometry}
        material={materials.Camera_Pixel_Glass_002}
        position={[0, 0, 0.043]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes.defaultMaterial007.geometry}
        material={materials.Camera_Pixel__002}
        position={[0, 0, 0.043]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes.defaultMaterial009.geometry}
        material={materials.Rim_Buttons}
        position={[0, 0, 0.043]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes.defaultMaterial010.geometry}
        material={materials.Flash_Glass_002}
        position={[-0.621, 1.715, -0.092]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.029}
      />
      <mesh
        geometry={nodes.defaultMaterial011.geometry}
        material={materials.Flash_002}
        position={[-0.621, 1.715, -0.08]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.029}
      />
      <mesh
        geometry={nodes.defaultMaterial012.geometry}
        position={[0, 0, 0.043]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.defaultMaterial013.geometry}
        material={materials.Screw}
        position={[0, 0, 0.043]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes.defaultMaterial014.geometry}
        material={materials.Screen_Glass}
        position={[0.609, 1.661, -0.14]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.027}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials["Material.001"]}
        position={[0, 0, 0.126]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.827}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials["Material.003"]}
        position={[0, 0, 0.126]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.827}
      />
    </group>
  );
}

useGLTF.preload("/model/17pro-transformed.glb");
